DROP TABLE IF EXISTS hit;

CREATE TABLE IF NOT EXISTS hit
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        VARCHAR(1024)                           NOT NULL,
    uri        VARCHAR(1024)                           NOT NULL,
    ip         VARCHAR(1024)                           NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);