DROP TABLE IF EXISTS hit;

CREATE TABLE hit
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        VARCHAR(512)                           NOT NULL,
    uri        VARCHAR(512)                           NOT NULL,
    ip         VARCHAR(32)                           NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);