version: '3.1'
services:
  stats-server:
    build: ./stats-service
    container_name:
      stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    env_file:
      - stats.env

  stats-db:
    image: postgres:14-alpine
    container_name:
      stats-db
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - stats-db.env

  ewm-service:
    build: ./main-service
    container_name:
      ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    env_file:
      - ewm-service.env

  ewm-db:
   image: postgres:14-alpine
   container_name:
     ewm-db
   volumes:
     - /var/lib/postgresql/data/
   env_file:
     - ewm-db.env